### ISSUE TITLE
Prototipo visual básico de la vista del detalle de un viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#19]
Story: #12 

### Descripción
Prototipo visual simple basado en wireframes. Definir la vista del detalle de un viaje, es decir, un usuario que ha hecho click desde cualquier parte de la web al elemento que representa un viaje.

#### Tareas
- [x] Especificar como se verá la lista de actividades de un viaje
- [x] Especificar como se accede y como se ve la opción para crear una nueva actividad en el viaje.
- [x] Especificar como se vota una actividad.

**Comment by diegorodrguez7** [comment]
Hemos acabado la tarea de la story 12 de diseño de la página web. Decidimos implementar un carousel para cambiar de días dentro del viaje. Justo debajo, si pulsas un botón, dinámicamente te sale el itinerario de ese día en concreto en el que estás. Seguidamente, justo debajo, "estilo blog", todas las fotos de ese viaje con su descripción.
