### ISSUE TITLE
Convertir diagrama entidad relación al modelo relacional

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#24]
Story: #13 

### Descripción
A partir del [diagrama entidad relación](https://miro.com/app/board/uXjVPhZ9TWA=/?share_link_id=372144463275) convertirlo al modelo relacional y definir el DBML de la documentación de la base de datos para alojar en dbdocs.io

#### Tareas
- [x] Convertir diagrama entidad relación a modelo relacional
- [x] Definir modelo en DBML para dbdocs.io

**Comment by DiegoBritoSanchez** [comment]
Enlace al diagrama generado en dbdocs.io: https://dbdiagram.io/d/640767a2296d97641d862392
