### ISSUE TITLE
Crear vista de la portada del sitio web para un usuario autenticado

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#40]
Story: #39 

### Descripción
Creación e implementación de la vista de la portada del sitio web para el usuario que ha hecho login.

**Comment by saurondk** [comment]
- [ ] Función principal que crea el contenido de la página
- [ ] Hace una solicitud a la URL definida anteriormente usando fetchDatos() y espera a que se complete la solicitud para crear tarjetas de viaje.
- [ ]  Hace una solicitud a la URL utilizando fetch() y devuelve los datos en formato JSON.
- [ ] Crea una tarjeta de viaje para cada elemento del objeto JSON devuelto por la función fetchDatos()
- [ ]    Agrega los elementos a la tarjeta de viaje

**Comment by saurondk** [comment]
- [ ]Implementar css
