### ISSUE TITLE
Crear header del sitio web 

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#43]
Story: #42 

### Descripción
Implementar el header o encabezado de la web con el menú. Sería conveniente crear una plantilla que se pueda reutilizar o algun JS que permita renderizar este componente en todas las páginas que lo requieran.

### Tareas
- [x] Crear encabezado de la web en un fichero aislado
- [x] Crear javascript que permita el renderizado dinamico del componente web en cualquier parte del sitio.
- [ ] Implementar logout de un usuario autenticado, simular petición de logout a la API.

**Comment by JSanJuan21** [comment]
Falta implementar el logout
