### ISSUE TITLE
S2.6 Los usuarios pueden ver el detalle de un viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#46]
Epic: #32 

### Descripción
Hay que implementar la vista relacionada con el detalle de un viaje que el usuario haya seleccionado.

### Tareas
- [x] Implementar vista del detalle de un viaje.
  - [x] Simular que recogemos datos del servidor con fetch y renderizamos los datos con los que nos ha respondido.

- [x] Falta implementar Css equipo diseño.

**Comment by diegorodrguez7** [comment]
- [ ] Obtener los datos por medio de una petición mediante fetch()
- [ ] Renderizar los días del viaje con sus actividades.
- [ ] Renderizar la lista de itinerarios de cada actividad.
- [ ] Crear botones de borrar, editar y agregar actividad.
- [ ] Crear botones de borrar y editar que redireccionan a las diferentes vistas de editar ese viaje o borrar ese viaje.
- [ ] Lógica de hacer clic en un día y desplegar su itinerario de actividades.
