### ISSUE TITLE
Implementar vista del detalle de un viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#47]
Story: #46

### Descripción
Hay que implementar la vista relacionada con el detalle de un viaje que el usuario haya seleccionado

### Tareas
- [x] Implementar vista del detalle de un viaje.
  - [x] Simular que recogemos datos del servidor con fetch y renderizamos los datos con los que nos ha respondido.
  - [x]  Implementar Css equipo diseño.

**Comment by diegorodrguez7** [comment]
- [ ] He subido a sprint 2 la vista acabada de detalle de un viaje.
