### ISSUE TITLE
Implementar gestión de participantes vista detalle de viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#48]
Story: #46

### Descripción
Debemos implementar la gestión de los participantes en la vista del detalle de un viaje siempre y cuando el viaje se encuentre abierto y el usuario sea autor del mismo.

### Tareas
- [x] Implementar vista del detalle de un viaje.
  - [x] Simular que recogemos datos del servidor con fetch y renderizamos los datos con los que nos ha respondido.

**Comment by diegorodrguez7** [comment]
- [ ] Referente a lo hablado en la reunión del equipo de desarrollo el día 10/03/2023 hemos decidido que en la vista detalle de un viaje no vamos a implementar la gestión de amigos/participantes dentro del mismo.
