### ISSUE TITLE
Implementar vista Mis Viajes

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#50]
Story: #49

### Descripción
Debemos implementar la vista asociada a Mis Viajes para que el usuario pueda ver un listado de los viajes que le pertenecen así como los viajes de los que forma parte.

### Tareas
- [x] Implementar vista Mis Viajes.
  - [x] Simular datos obtenidos y mostrar viajes creados por el usuario.
  - [x] Simular datos obtenidos y mostrar viajes en los que ha participado el usuario.
  - [x] Implementar css.

- Refinamientos de la vista necesarios: #61 
  - [x] Es posible acceder a la edición de cualquiera de los viajes de los que el usuario es autor.
  - [x] Es posible acceder a la eliminación de cualquier de los viajes de los que el usuario es autor.

**Comment by jraicr** [comment]
@Marco1080 Aquí falta el refinamiento del issue #61

**Comment by Marco1080** [comment]
He añadido los botones correspondientes y agregado al boton editar la dirección de la vista para editar viajes.
