### ISSUE TITLE
Implementar vista mis amigos

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#57]
Story: #51

### Descripción
Hay que implementar la vista mis amigos desde donde gestionaremos las conexiones entre los usuarios.

### Tareas
 - [x] Simular la obtención de la lista de datos de amigos del usuario desde la API
  - [x] Renderizar listado de amigos
  - [x] Implementar CSS

**Comment by jraicr** [comment]
Diría que se podría simplificar la solicitud de datos a la API en una sola llamada, para listar todos los amigos que ya tiene el usuario

La API podría tener un endpoint que te devuelva la lista de amigos de un usuario
 - http://ruta.com/user/friends 

Esta API puede responder con get 
GET -> /{user_id}/friends

**Comment by DiegoBritoSanchez** [comment]
Corregido el FETCH para que simular que lleguen solo aquellos con o bien son amigos del usuario logeado, o bien tienen la solicitud pendiente de ser aceptada
