### ISSUE TITLE
Implementar gestión de solicitudes en vista Mis Amigos

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#58]
Story: #51

### Descripción
Hay que implementar la gestión de las solicitudes de amistad que realizan al usuario desde la vista Mis Amigos

### Tareas
- [x] Simular obtención de solicitudes de amistad que nos han enviado
  - [x]  Renderizar solicitudes de amistad
  - [x] Simular que datos enviamos al servidor si aceptamos solicitud
  - [x] Simular que datos enviamos al servidor si denegamos la solicitud

**Comment by DiegoBritoSanchez** [comment]
Preparados los FETCH para en caso de aceptar/rechazar la solicitud le llegue al servidor mediante el formato del id y el estado de la relación entre el usuario logeado y la solicitud de amistad. Se enviará un true para confirmarla y un false para eliminar el registro de dicha solicitud.
