### ISSUE TITLE
Implementar eliminación de amigo en vista Mis Amigos

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#60]
Story: #51

### Descripción
Hay que implementar la eliminación de amigos desde el listado de la vista Mis Amigos

### Tareas
- [x] Implementar eliminación amigos
  - [x] Simular que enviamos petición de eliminación de amigo a la API

**Comment by DiegoBritoSanchez** [comment]
Al igual que en el manejo de la solicitud de amistad, en caso de que el usuario rechace una solicitud se enviará al servidor el ID representativo de dicha relación y un false para eliminar el registro de la tabla correspondiente
