### ISSUE TITLE
Falta acceso a edición y eliminación de viajes en vistas Mis Viajes y en el detalle de Viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#61]
He detectado en los diseños de Figma que no tenemos forma de editar o eliminar viajes desde las vistas Mis Viajes y el detalle de un viaje. 

Debemos de tener en cuenta esto cuando nos toque implementar estas vistas. 

- [x] Corregir vista del detalle de un viaje
- [x] Corregir vista de Mis Viajes

**Comment by jraicr** [comment]
De acuerdo @DiegoBritoSanchez , buen trabajo! 

@Marco1080  faltaría tenerlo en cuenta para la vista de "Mis Viajes"

**Comment by diegorodrguez7** [comment]
Disculpa @jraicr pero mi nombre es Diego Rodriguez. Buen día, un saludo.

**Comment by jraicr** [comment]
> Disculpa @jraicr pero mi nombre es Diego Rodriguez. Buen día, un saludo. 

Perdona, mencioné por error al otro Diego xD
