### ISSUE TITLE
Ni en la vista de Mis Viajes ni en la de Viaje tenemos forma de saber el estado del mismo

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#62]
He detectado que en las vistas de prototipo diseñadas en Figma no tenemos una forma de comprobar cual es el estado de un viaje, por lo que debemos de tener en cuenta esto a la hora de implementar la vista

- [x] Corregir vista detalle de un viaje
- [x] Corregir vista Mis Viajes

**Comment by diegorodrguez7** [comment]
Yo ya he actualizado este paso. He añadido un contenedor donde se podrá recoger el estado del viaje (de momento recogiendo "en curso" desde un data.json) en la vista que yo estoy creando. (detalle de un viaje). Adjunto imagen.

![Image](https://user-images.githubusercontent.com/93778802/224179207-5a139c33-ddd8-4c6d-86e5-c7cb80fa179e.JPG)

**Comment by jraicr** [comment]
Perfecto, buen trabajo Diego.

Faltaría tenerlo en cuenta para la vista **Mis Viajes**, tenlo en cuenta @Marco1080

**Comment by Marco1080** [comment]
He corregido mi vista y ahora se ve el estado de los viajes.
