### ISSUE TITLE
Falta poder añadir más participantes en la vista del detalle de un viaje

### ISSUE THREAD

**Issue by jraicr** [JulessZ/InstaViajes#63]
He detectado que en la vista de prototipo de Figma de ver el detalle de un viaje no tenemos forma de añadir a nuevos participantes, necesitamos tenerlo en cuenta a la hora de implementar esta vista.

**Comment by diegorodrguez7** [comment]
- [ ] Como hemos recalcado en el task #48 , no vamos a implementar la gestión de participantes.
